namespace CodeChallenges2
{
    internal class FibEvenSum
    {
        static void Main(string[] args)
        {

            //Each new term in the Fib sequence is generated by adding the previous 2 terms.
            //By starting with 1 and 2, the first 2 terms will be:
            // 1,2,3,5,8,13,21,34,55,89,...

            //By considering the terms in the Fib sequence whose values do not exceed 4 million, find the sum of the even-valued terms.

            Console.WriteLine("----- Fibocacci Sequence: Even Sum -----\n\n");
            

            bool exit=false;
            List<int> fibSeq = new List<int>() { 1, 2 };
            int start = 1;
            int fibNbr = start;
            do
            {
                if (fibNbr <= 4_000_000)
                {
                    fibNbr = fibSeq[fibSeq.Count - 1] + fibSeq[fibSeq.Count - 2];
                    fibSeq.Add(fibNbr);
                    Console.WriteLine(fibSeq[fibSeq.Count - 1]);
                }
                else
                {
                    exit = true;
                }

            } while (!exit);
            var fibSeqEven = fibSeq.Where(x => x % 2 ==0).ToList();
            Console.WriteLine(fibSeqEven.Sum());

        }//end Main()
    }//end class
}//end namespace